=== mousterchung/backup_data_from_desktop/web/xml/dtd/mrt.dtd
<!ELEMENT mrt (xhtml:script, line*)>					<!--root-->
	<!ATTLIST mrt place-zhtw  CDATA>
	<!ATTLIST mrt place-en    CDATA>
	<!ATTLIST mrt xmlns:xhtml #FIXED http://www.w3.org/1999/xhtml>
	
	<!ELEMENT line (line-name-zhtw, line-name-en, line-name-ja, line-name-ko, station*)>
		<!ATTLIST line line-id       ID           #REQUIRED>
		<!ATTLIST line line-color-bg CDATA        #REQUIRED>
		<!ATTLIST line line-color-fg CDATA        #REQUIRED>
		<!ATTLIST line no-service    (true|false) false>
		
		<!ELEMENT line-name-zhtw #PCDATA>
		<!ELEMENT line-name-en   #PCDATA>
		<!ELEMENT line-name-ja   #PCDATA>
		<!ELEMENT line-name-ko   #PCDATA>
		<!ELEMENT station (sta-name-zhtw, sta-name-en, sta-name-ja, sta-name-ko, transfers)>
			<!ATTLIST station sta-id      ID          #REQUIRED>
			<!ATTLIST station no-service (true|false) false>
			
			<!ELEMENT sta-name-zhtw     #PCDATA>
			<!ELEMENT sta-name-en       #PCDATA>
			<!ELEMENT sta-name-ja       #PCDATA>
			<!ELEMENT sta-name-ko       #PCDATA>
			<!ELEMENT transfers         (transfer*)>
				<!ELEMENT transfer          (transfer-line, transfer-line-sta)>
					<!ATTLIST transfer no-service (true|false) false>
					<!ATTLIST transfer out-of-sta (true|false) false>
					
					<!ELEMENT transfer-line     #PCDATA>
						<!ATTLIST transfer-line IDREF #REQUIRED>
					<!ELEMENT transfer-line-sta #PCDATA>
						<!ATTLIST transfer-line-sta IDREF #REQUIRED>

=== mousterchung/backup_data_from_desktop/web/xml/mrt_taipei.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<?xml-stylesheet href="./xsl/mrt.xsl" type="text/xsl"?>-->
<?xml-stylesheet href="./../css/mrt.css" type="text/css"?>
<!DOCTYPE mrt SYSTEM "./dtd/mrt.dtd">
<mrt place-zhtw="台北" place-en="taipei" xmlns:xhtml="http://www.w3.org/1999/xhtml">
	<xhtml:script type="text/javascript" src="./../js/css_attr.js"></xhtml:script>
	<line line-id="taipei-br" line-color-bg="#c48c31" line-color-fg="white">
		<line-name-zhtw>文湖線</line-name-zhtw>
		<line-name-en>Wenhu Line</line-name-en>
		<line-name-ja>文湖線</line-name-ja>
		<line-name-ko>원후 선</line-name-ko>
		<station sta-id="taipei-br01">
			<sta-name-zhtw>動物園</sta-name-zhtw>
			<sta-name-en>Taipei Zoo</sta-name-en>
			<sta-name-ja>動物園</sta-name-ja>
			<sta-name-ko>동물원</sta-name-ko>
			<transfers>
				<transfer no-service="true">
					<transfer-line transfer-line="newtaipei-y">環狀線</transfer-line>
					<transfer-line-sta transfer-line-sta="newtaipei-y01">動物園</transfer-line-sta>
				</transfer>
				<transfer no-service="true" out-of-sta="true">
					<transfer-line transfer-line="newtaipei-s">深坑輕軌</transfer-line>
					<transfer-line-sta transfer-line-sta="newtaipei-s1">動物園</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
		<station sta-id="taipei-br02">
			<sta-name-zhtw>木柵</sta-name-zhtw>
			<sta-name-en>Muzha</sta-name-en>
			<sta-name-ja>木柵</sta-name-ja>
			<sta-name-ko>무자</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br03">
			<sta-name-zhtw>萬芳社區</sta-name-zhtw>
			<sta-name-en>Wanfang Community</sta-name-en>
			<sta-name-ja>万芳コミュニティ</sta-name-ja>
			<sta-name-ko>완팡 단지</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br04">
			<sta-name-zhtw>萬芳醫院</sta-name-zhtw>
			<sta-name-en>Wanfang Hospital</sta-name-en>
			<sta-name-ja>万芳病院</sta-name-ja>
			<sta-name-ko>완팡 병원</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br05">
			<sta-name-zhtw>辛亥</sta-name-zhtw>
			<sta-name-en>Xinhai</sta-name-en>
			<sta-name-ja>辛亥</sta-name-ja>
			<sta-name-ko>신하이</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br06">
			<sta-name-zhtw>麟光</sta-name-zhtw>
			<sta-name-en>Linguang</sta-name-en>
			<sta-name-ja>麟光</sta-name-ja>
			<sta-name-ko>린광</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br07">
			<sta-name-zhtw>六張犁</sta-name-zhtw>
			<sta-name-en>Liuzhangli</sta-name-en>
			<sta-name-ja>六張犁</sta-name-ja>
			<sta-name-ko>류장리</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br08">
			<sta-name-zhtw>科技大樓</sta-name-zhtw>
			<sta-name-en>Technology Building</sta-name-en>
			<sta-name-ja>テクノロジービル</sta-name-ja>
			<sta-name-ko>테크놀로지 빌딩</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br09">
			<sta-name-zhtw>大安</sta-name-zhtw>
			<sta-name-en>Daan</sta-name-en>
			<sta-name-ja>大安</sta-name-ja>
			<sta-name-ko>다안</sta-name-ko>
			<transfers>
				<transfer>
					<transfer-line transfer-line="taipei-r">淡水信義線</transfer-line>
					<transfer-line-sta transfer-line-sta="taipei-r05">大安</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
		<station sta-id="taipei-br10">
			<sta-name-zhtw>忠孝復興</sta-name-zhtw>
			<sta-name-en>Zhongxiao Fuxing</sta-name-en>
			<sta-name-ja>忠孝復興</sta-name-ja>
			<sta-name-ko>중샤오 푸싱</sta-name-ko>
			<transfers>
				<transfer>
					<transfer-line transfer-line="taipei-bl">板南線</transfer-line>
					<transfer-line-sta transfer-line-sta="taipei-bl15">忠孝復興</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
		<station sta-id="taipei-br11">
			<sta-name-zhtw>南京復興</sta-name-zhtw>
			<sta-name-en>Nanjing Fuxing</sta-name-en>
			<sta-name-ja>南京復興</sta-name-ja>
			<sta-name-ko>난징 푸싱</sta-name-ko>
			<transfers>
				<transfer>
					<transfer-line transfer-line="taipei-g">松山新店線</transfer-line>
					<transfer-line-sta transfer-line-sta="taipei-g16">南京復興</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
		<station sta-id="taipei-br12">
			<sta-name-zhtw>中山國中</sta-name-zhtw>
			<sta-name-en>Zhongshan Junior High School</sta-name-en>
			<sta-name-ja>中山中学校</sta-name-ja>
			<sta-name-ko>중산 중학교</sta-name-ko>
			<transfers>
				<transfer no-service="true" out-of-sta="true">
					<transfer-line transfer-line="taipei-sb">民生汐止線</transfer-line>
					<transfer-line-sta transfer-line-sta="taipei-sb04">（站名未定）</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
		<station sta-id="taipei-br13">
			<sta-name-zhtw>松山機場</sta-name-zhtw>
			<sta-name-en>Songshan Airport</sta-name-en>
			<sta-name-ja>松山空港</sta-name-ja>
			<sta-name-ko>송산 공항</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br14">
			<sta-name-zhtw>大直（實踐大學）</sta-name-zhtw>
			<sta-name-en>Dazhi ( Shih Chien University )</sta-name-en>
			<sta-name-ja>大直</sta-name-ja>
			<sta-name-ko>다즈</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br15">
			<sta-name-zhtw>劍南路（美麗華）</sta-name-zhtw>
			<sta-name-en>Jiannan Road ( Miramar )</sta-name-en>
			<sta-name-ja>剣南路</sta-name-ja>
			<sta-name-ko>젠난루</sta-name-ko>
			<transfers>
				<transfer no-service="true">
					<transfer-line transfer-line="newtaipei-y">環狀線</transfer-line>
					<transfer-line-sta transfer-line-sta="newtaipei-y30">劍南路（美麗華）</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
		<station sta-id="taipei-br16">
			<sta-name-zhtw>西湖（德明科大）</sta-name-zhtw>
			<sta-name-en>Xihu ( Takming University )</sta-name-en>
			<sta-name-ja>西湖</sta-name-ja>
			<sta-name-ko>시후</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br17">
			<sta-name-zhtw>港墘</sta-name-zhtw>
			<sta-name-en>Gangqian</sta-name-en>
			<sta-name-ja>港墘</sta-name-ja>
			<sta-name-ko>강첸</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br18">
			<sta-name-zhtw>文德（碧湖公園）</sta-name-zhtw>
			<sta-name-en>Wende ( Bihu Park )</sta-name-en>
			<sta-name-ja>文徳</sta-name-ja>
			<sta-name-ko>원더</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br19">
			<sta-name-zhtw>內湖</sta-name-zhtw>
			<sta-name-en>Neihu</sta-name-en>
			<sta-name-ja>内湖</sta-name-ja>
			<sta-name-ko>네이후</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br20">
			<sta-name-zhtw>大湖公園</sta-name-zhtw>
			<sta-name-en>Dahu Park</sta-name-en>
			<sta-name-ja>大湖公園</sta-name-ja>
			<sta-name-ko>다후 공원</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br21">
			<sta-name-zhtw>葫洲</sta-name-zhtw>
			<sta-name-en>Huzhou</sta-name-en>
			<sta-name-ja>葫洲</sta-name-ja>
			<sta-name-ko>후저우</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br22">
			<sta-name-zhtw>東湖</sta-name-zhtw>
			<sta-name-en>Donghu</sta-name-en>
			<sta-name-ja>東湖</sta-name-ja>
			<sta-name-ko>둥후</sta-name-ko>
			<transfers>
				<transfer no-service="true">
					<transfer-line transfer-line="taipei-sb">民生汐止線</transfer-line>
					<transfer-line-sta transfer-line-sta="taipei-sb10">東湖</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
		<station sta-id="taipei-br23">
			<sta-name-zhtw>南港軟體園區</sta-name-zhtw>
			<sta-name-en>Nangang Software Park</sta-name-en>
			<sta-name-ja>南港ソフトウェアパーク</sta-name-ja>
			<sta-name-ko>난강 소프트웨어 단지</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-br24">
			<sta-name-zhtw>南港展覽館</sta-name-zhtw>
			<sta-name-en>Taipei Nangang Exibition Center</sta-name-en>
			<sta-name-ja>南港展覧館</sta-name-ja>
			<sta-name-ko>난강 전람관</sta-name-ko>
			<transfers>
				<transfer>
					<transfer-line transfer-line="taipei-bl">板南線</transfer-line>
					<transfer-line-sta transfer-line-sta="taipei-bl23">南港展覧館</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
	</line>
	
	<line line-id="taipei-r" line-color-bg="#e3002c" line-color-fg="white">
		<line-name-zhtw>淡水信義線</line-name-zhtw>
		<line-name-en>Tamsui-Xinyi Line</line-name-en>
		<line-name-ja>淡水信義線</line-name-ja>
		<line-name-ko>단수이-신이 선</line-name-ko>
		<station sta-id="taipei-r01" no-service="true">
			<sta-name-zhtw>廣慈／奉天宮</sta-name-zhtw>
			<sta-name-en>Guangci / Fengtian Temple</sta-name-en>
			<sta-name-ja>広慈／奉天宮</sta-name-ja>
			<sta-name-ko>광츠 / 펑톈궁</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-r02">
			<sta-name-zhtw>象山</sta-name-zhtw>
			<sta-name-en>Xiangshan</sta-name-en>
			<sta-name-ja>象山</sta-name-ja>
			<sta-name-ko>샹산</sta-name-ko>
			<transfers>
				<transfer no-service="true" out-of-sta="true">
					<transfer-line transfer-line="newtaipei-y">環狀線</transfer-line>
					<transfer-line-sta transfer-line-sta="newtaipei-y39">象山</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
		<station sta-id="taipei-r03">
			<sta-name-zhtw>台北１０１／世貿</sta-name-zhtw>
			<sta-name-en>Taipei 101 / World Trade Center</sta-name-en>
			<sta-name-ja>台北１０１／世界貿易センター</sta-name-ja>
			<sta-name-ko>타이베이101 / 세계무역센터</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-r04">
			<sta-name-zhtw>信義安和</sta-name-zhtw>
			<sta-name-en>Xinyi Anhe</sta-name-en>
			<sta-name-ja>信義安和</sta-name-ja>
			<sta-name-ko>신이 안허</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-r05">
			<sta-name-zhtw>大安</sta-name-zhtw>
			<sta-name-en>Daan</sta-name-en>
			<sta-name-ja>大安</sta-name-ja>
			<sta-name-ko>다안</sta-name-ko>
			<transfers>
				<transfer>
					<transfer-line transfer-line="taipei-br">文湖線</transfer-line>
					<transfer-line-sta transfer-line-sta="taipei-br09">大安</transfer-line-sta>
				</transfer>
			</transfers>
		</station>
		<station sta-id="taipei-r06">
			<sta-name-zhtw>大安森林公園</sta-name-zhtw>
			<sta-name-en>Daan Park</sta-name-en>
			<sta-name-ja>大安森林公園</sta-name-ja>
			<sta-name-ko>다안 삼림 공원</sta-name-ko>
			<transfers>
			</transfers>
		</station>
		<station sta-id="taipei-r07">
