=== mousterchung/backup_data_from_desktop/web/xml/dtd/mrt_stalist.dtd
<!ELEMENT mrt-stalist (group*)>							<!--root-->
	<!ELEMENT group (sta*)>
		<!ATTLIST group letter CDATA>
		
		<!ELEMENT sta (sta-name-zhtw, sta-name-en, sta-number*)>
			<!ELEMENT sta-name-zhtw #PCDATA>
			<!ELEMENT sta-name-en   #PCDATA>
			<!ELEMENT sta-number    EMPTY>
				<!ATTLIST sta-number
				<!ATTLIST sta-number
				<!ATTLIST sta-number

=== mousterchung/backup_data_from_desktop/web/xml/mrt_stalist_en_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./../css/mrt_stalist_xml.css" type="text/css"?>
<!DOCTYPE mrt-stalist SYSTEM "./dtd/mrt_stalist.dtd">
<mrt-stalist>
	<group letter="Ａ">
		
	</group>
	<group letter="Ｂ">
		
	</group>
	<group letter="Ｃ">
		
	</group>
	<group letter="Ｄ">
		
	</group>
	<group letter="Ｅ">
		
	</group>
	<group letter="Ｆ">
		
	</group>
	<group letter="Ｇ">
		
	</group>
	<group letter="Ｈ">
		
	</group>
	<group letter="Ｉ">
		
	</group>
	<group letter="Ｊ">
		
	</group>
	<group letter="Ｋ">
		
	</group>
	<group letter="Ｌ">
		
	</group>
	<group letter="Ｍ">
		
	</group>
	<group letter="Ｎ">
		
	</group>
	<group letter="Ｏ">
		
	</group>
	<group letter="Ｐ">
		
	</group>
	<group letter="Ｑ">
		
	</group>
	<group letter="Ｒ">
		
	</group>
	<group letter="Ｓ">
		
	</group>
	<group letter="Ｔ">
		
	</group>
	<group letter="Ｕ">
		
	</group>
	<group letter="Ｖ">
		
	</group>
	<group letter="Ｗ">
		
	</group>
	<group letter="Ｘ">
		
	</group>
	<group letter="Ｙ">
		
	</group>
	<group letter="Ｚ">
		
	</group>
	<group letter="＊">
		
	</group>
</mrt-stalist>

=== mousterchung/backup_data_from_desktop/web/xml/mrt_bigtaipei_stalist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mrt-stalist SYSTEM "./dtd/mrt_stalist.dtd">
<mrt-stalist>
	<group letter="A">
		
	</group>
	<group letter="B">
		
	</group>
	<group letter="C">
		
	</group>
	<group letter="D">
		
	</group>
	<group letter="E">
		
	</group>
	<group letter="F">
		
	</group>
	<group letter="G">
		
	</group>
	<group letter="H">
		
	</group>
	<group letter="I">
		
	</group>
	<group letter="J">
		
	</group>
	<group letter="K">
		
	</group>
	<group letter="L">
		
	</group>
	<group letter="M">
		
	</group>
	<group letter="N">
		
	</group>
	<group letter="O">
		
	</group>
	<group letter="P">
		
	</group>
	<group letter="Q">
		
	</group>
	<group letter="R">
		
	</group>
	<group letter="S">
		
	</group>
	<group letter="T">
		<sta>
			<sta-name-zhtw>台北車站</sta-name-zhtw>
			<sta-name-en>Taipei Main Station</sta-name-en>
			<sta-numbers>
				<sta-number place="TP" route="R" stano="10"/>
				<sta-number place="TP" route="BL" stano="12"/>
				<sta-number place="TY" route="A" stano="1"/>
			</sta-numbers>
		</sta>
	</group>
	<group letter="U">
		
	</group>
	<group letter="V">
		
	</group>
	<group letter="W">
		
	</group>
	<group letter="X">
		
	</group>
	<group letter="Y">
		
	</group>
	<group letter="Z">
		
	</group>
</mrt-stalist>

=== mousterchung/backup_data_from_desktop/web/xml/mrt_stalist_zhtw_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./../css/mrt_stalist_xml.css" type="text/css"?>
<!DOCTYPE mrt-stalist SYSTEM "./dtd/mrt_stalist.dtd">
<mrt-stalist>
	<group letter="ㄅ">
		
	</group>
	<group letter="ㄆ">
		
	</group>
	<group letter="ㄇ">
		
	</group>
	<group letter="ㄈ">
		
	</group>
	<group letter="ㄉ">
		
	</group>
	<group letter="ㄊ">
		
	</group>
	<group letter="ㄋ">
		
	</group>
	<group letter="ㄌ">
		
	</group>
	<group letter="ㄍ">
		
	</group>
	<group letter="ㄎ">
		
	</group>
	<group letter="ㄏ">
		
	</group>
	<group letter="ㄐ">
		
	</group>
	<group letter="ㄑ">
		
	</group>
	<group letter="ㄒ">
		
	</group>
	<group letter="ㄓ">
		
	</group>
	<group letter="ㄔ">
		
	</group>
	<group letter="ㄕ">
		
	</group>
	<group letter="ㄖ">
		
	</group>
	<group letter="ㄗ">
		
	</group>
	<group letter="ㄘ">
		
	</group>
	<group letter="ㄙ">
		
	</group>
	<group letter="ㄧ">
		
	</group>
	<group letter="ㄨ">
		
	</group>
	<group letter="ㄩ">
		
	</group>
	<group letter="ㄚ">
		
	</group>
	<group letter="ㄛ">
		
	</group>
	<group letter="ㄜ">
		
	</group>
	<group letter="ㄝ">
		
	</group>
	<group letter="ㄞ">
		
	</group>
	<group letter="ㄟ">
		
	</group>
	<group letter="ㄠ">
		
	</group>
	<group letter="ㄡ">
		
	</group>
	<group letter="ㄢ">
		
	</group>
	<group letter="ㄣ">
		
	</group>
	<group letter="ㄤ">
		
	</group>
	<group letter="ㄥ">
		
	</group>
	<group letter="ㄦ">
		
	</group>
	<group letter="＊">
		
	</group>
</mrt-stalist>
